### ISSUE TITLE
Missing Icons & Lag When Opening/Closing Settings

### ISSUE THREAD

**Issue by gayfrogog** [ricewind012/discord-gnome-theme#6]
There are some visibly missing icons in the main screen. The icons for the "Upload" button and the other button that makes you purchase Nitro are missing under the typing bar. 
![image](https://github.com/user-attachments/assets/64cc823d-3e94-435d-b30b-68e0d00cbf08)

Additionally, there is significant lag when you close and open the settings menu. #3 seems to help but it's still significant.

**Comment by ricewind012** [comment]
I merged #3 - it may seem like lag, but it's rather discord animations not appearing, it opens with the exact same speed

**Comment by gayfrogog** [comment]
Thanks for clarifying on that. The icons are functioning now. Thanks for the theme :+1:
